// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

List<NatoEntryDto> convertNato({required String input}) =>
    RustLib.instance.api.crateApiConvertNato(input: input);

class NatoEntryDto {
  final String character;
  final String? word;

  const NatoEntryDto({required this.character, this.word});

  @override
  int get hashCode => character.hashCode ^ word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NatoEntryDto &&
          runtimeType == other.runtimeType &&
          character == other.character &&
          word == other.word;
}
