[package]
name              = "nato"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Convert text to NATO phonetic alphabet"
readme      = "../../README.md"
keywords    = ["nato", "phonetic", "alphabet", "cli"]
categories  = ["command-line-utilities"]

[dependencies]
